name: "歌词反馈"
description: "歌词问题"
labels: [Bug]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "**我已确认我使用的是最新版本的 LRC，最新版 LRC 仍然存在此问题。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述具体表现。"
    placeholder: "样例：这个问题具体表现是软件显示的歌词与音频对不上/存在错别字"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: "这个问题发生的时间节点，发生于哪个 LRC"
    description: "这个 Bug 发生的时间段"
    placeholder: "样例：这个问题发生大哉乾元的歌词文件中，在 1:45/在xxxx段。"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 附件
    description: "在这里上传截图、LRC、音频文件"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: false