name: "歌词反馈"
description: "歌词问题"
labels: [· Bug, 新反馈]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "**我已确认我使用的是最新版本的 LRC，最新版 LRC 仍然存在此问题。"
      required: true
    - label: "**我使用的软件是最新版本，此软件最新版本无法正常识别/校对歌词时间节点，且这个软件有足够庞大的用户社群并正在维护"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/LTY-Followers/LuoTianyiCoverSongLRC/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。"
      required: true
    - label: "我确认这个音频没有人为的截短或加速"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述具体表现。"
    placeholder: "样例：这个问题具体表现是软件显示的歌词与音频对不上/存在错别字"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 这个问题发生的时间节点
    description: "这个 Bug 发生的时间段"
    placeholder: "样例：这个问题发生在 1:45 ，在xxxx段。"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 附件
    description: "在这里上传截图、LRC、音频文件"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: true