name: deply to page
on:
  workflow_dispatch:


permissions:
  contents: write

jobs:

  build:

    runs-on: windows-2022
    
    steps: 

      - name: CheckOut Code
        uses: actions/checkout@v4
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: ./
          CLEAN: true
  