name: GitHubIssueCheck

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      
      - name: Run Check
        run: python Check-Code.py --apikey ${{secerts.TOKEN}} --blocklist https://issue-meta.luolingxue.us.kg/blockuser.json